config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get 'generate_fake_users'
    end
  end
  resources :job_offers
  # Otras rutas que puedas necesitar
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: %i[ show edit update destroy ]

  # GET /job_offers or /job_offers.json
  def index
    @job_offers = JobOffer.all
  end

  # GET /job_offers/1 or /job_offers/1.json
  def show
  end

  # GET /job_offers/new
  def new
    @job_offer = JobOffer.new
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers or /job_offers.json
  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully created." }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_offers/1 or /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully updated." }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_offers/1 or /job_offers/1.json
  def destroy
    @job_offer.destroy

    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: "Job offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_offer_params
      params.require(:job_offer).permit(:title, :description, :requirements, :status, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
  
    # GET /users or /users.json
    def index
      @users = User.all
    end
  
    # GET /users/1 or /users/1.json
    def show
    end
  
    # GET /users/new
    def new
      @user = User.new
    end
  
    # GET /users/1/edit
    def edit
    end
  
    # POST /users or /users.json
    def create
      @user = User.new(user_params)
  
      respond_to do |format|
        if @user.save
          format.html { redirect_to user_url(@user), notice: "User was successfully created." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1 or /users/1.json
    def destroy
      @user.destroy
  
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    # Custom action to generate fake users
    def generate_fake_users
      10.times do
        User.create!(
          nombre: Faker::Name.first_name,
          apellido: Faker::Name.last_name,
          correo_electronico: Faker::Internet.email,
          foto_de_perfil: Faker::Avatar.image,
          otros_datos: Faker::Lorem.sentence
        )
      end
  
      redirect_to users_path, notice: 'Usuarios ficticios creados exitosamente.'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:nombre, :apellido, :correo_electronico, :foto_de_perfil, :otros_datos)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/job_offers/_form.html.erb
<%= form_with(model: job_offer) do |form| %>
  <% if job_offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_offer.errors.count, "error") %> prohibited this job_offer from being saved:</h2>

      <ul>
        <% job_offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :requirements, style: "display: block" %>
    <%= form.text_area :requirements %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_offers/_job_offer.html.erb
<div id="<%= dom_id job_offer %>">
  <p>
    <strong>Title:</strong>
    <%= job_offer.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job_offer.description %>
  </p>

  <p>
    <strong>Requirements:</strong>
    <%= job_offer.requirements %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= job_offer.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= job_offer.user_id %>
  </p>

</div>

app/views/job_offers/edit.html.erb
<h1>Editing job offer</h1>

<%= render "form", job_offer: @job_offer %>

<br>

<div>
  <%= link_to "Show this job offer", @job_offer %> |
  <%= link_to "Back to job offers", job_offers_path %>
</div>

app/views/job_offers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Job offers</h1>

<div id="job_offers">
  <% @job_offers.each do |job_offer| %>
    <%= render job_offer %>
    <p>
      <%= link_to "Show this job offer", job_offer %>
    </p>
  <% end %>
</div>

<%= link_to "New job offer", new_job_offer_path %>

app/views/job_offers/new.html.erb
<h1>New job offer</h1>

<%= render "form", job_offer: @job_offer %>

<br>

<div>
  <%= link_to "Back to job offers", job_offers_path %>
</div>

app/views/job_offers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_offer %>

<div>
  <%= link_to "Edit this job offer", edit_job_offer_path(@job_offer) %> |
  <%= link_to "Back to job offers", job_offers_path %>

  <%= button_to "Destroy this job offer", @job_offer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPortalX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido %>
  </div>

  <div>
    <%= form.label :correo_electronico, style: "display: block" %>
    <%= form.text_field :correo_electronico %>
  </div>

  <div>
    <%= form.label :foto_de_perfil, style: "display: block" %>
    <%= form.text_field :foto_de_perfil %>
  </div>

  <div>
    <%= form.label :otros_datos, style: "display: block" %>
    <%= form.text_area :otros_datos %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Nombre:</strong>
    <%= user.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= user.apellido %>
  </p>

  <p>
    <strong>Correo electronico:</strong>
    <%= user.correo_electronico %>
  </p>

  <p>
    <strong>Foto de perfil:</strong>
    <%= user.foto_de_perfil %>
  </p>

  <p>
    <strong>Otros datos:</strong>
    <%= user.otros_datos %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>